'use strict';
// LAPI (lecture automatique de plaques) adapted from the French SIV format
// (AA-123-BB) to the Algerian format (NNNNNN-CAA-WW: numéro de série,
// catégorie + année d'immatriculation, code de wilaya 01-58, jamais de
// lettre) — both the OCR text parser (extrairePlaque, frontend/js/app.js)
// and the demo plate generator (generePlaque, frontend/js/ui.js).
const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');

const appSource = fs.readFileSync(path.resolve(__dirname, '../frontend/js/app.js'), 'utf8');
const uiSource = fs.readFileSync(path.resolve(__dirname, '../frontend/js/ui.js'), 'utf8');
const cssSource = fs.readFileSync(path.resolve(__dirname, '../frontend/css/style.css'), 'utf8');

// extrairePlaque() has no dependency beyond its own body — extracted and
// evaluated standalone rather than loading all of app.js, which touches
// `document` at the top level (nav wiring) and has no module.exports.
function loadExtrairePlaque() {
  const start = appSource.indexOf('function extrairePlaque');
  assert.ok(start !== -1, 'extrairePlaque not found in app.js');
  const end = appSource.indexOf('\n}\n', start) + 3;
  return new Function(appSource.slice(start, end) + '\nreturn extrairePlaque;')();
}

// generePlaque() lives in ui.js alongside randInt(), which it calls — both
// are plain top-level functions with no DOM dependency, loaded the same way
// tests/frontend-i18n-arabic.test.js already loads ui.js into a vm context.
function loadGenePlaque() {
  const context = vm.createContext({ Math });
  new vm.Script(uiSource, { filename: 'ui.js' }).runInContext(context);
  return new vm.Script('generePlaque').runInContext(context);
}

const ALGERIAN_PLATE = /^\d{4,6}-\d{3}-(0[1-9]|[1-4]\d|5[0-8])$/;

test('extrairePlaque recognizes the Algerian format (serial-category+year-wilaya)', () => {
  const extrairePlaque = loadExtrairePlaque();
  assert.equal(extrairePlaque('123456-114-16'), '123456-114-16');
  assert.equal(extrairePlaque('1234-101-01'), '1234-101-01');
  // OCR noise around a valid plate (spaces, stray punctuation) must not
  // prevent the match — mirrors how a real camera capture reads.
  assert.equal(extrairePlaque('  123456 - 114 - 16  '), '123456-114-16');
});

test('extrairePlaque rejects an out-of-range wilaya code (only 01 to 58 exist)', () => {
  const extrairePlaque = loadExtrairePlaque();
  // No letters anywhere in this string, so it cannot fall through to the
  // French or generic fallback branches either — must be null.
  assert.equal(extrairePlaque('123456-114-99'), null);
  assert.equal(extrairePlaque('123456-114-00'), null);
});

test('extrairePlaque still falls back to the older French formats (SIV/FNI) when no Algerian pattern matches', () => {
  const extrairePlaque = loadExtrairePlaque();
  assert.equal(extrairePlaque('AB-123-CD'), 'AB-123-CD');
  assert.equal(extrairePlaque('1234AB56'), '1234 AB 56');
});

test('generePlaque produces a well-formed Algerian plate every time', () => {
  const generePlaque = loadGenePlaque();
  for (let i = 0; i < 200; i++) {
    const plate = generePlaque();
    assert.match(plate, ALGERIAN_PLATE, plate);
  }
});

test('a plate generated by generePlaque round-trips through extrairePlaque unchanged', () => {
  const generePlaque = loadGenePlaque();
  const extrairePlaque = loadExtrairePlaque();
  for (let i = 0; i < 50; i++) {
    const plate = generePlaque();
    assert.equal(extrairePlaque(plate), plate);
  }
});

test('the plate mockup has no leftover French/EU country band (Algerian plates carry none)', () => {
  assert.doesNotMatch(cssSource, /\.plate-display::before/, 'the "FR" side band should be removed');
  assert.doesNotMatch(cssSource, /#003399|#fcd116/, 'French flag colors should not remain on the plate mockup');
});
