-- PG-2.2: historical business schema only. No seed or import.
-- Dates remain TEXT; only users.id historically auto-increments.
CREATE TABLE public.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    nom_complet TEXT,
    role TEXT DEFAULT 'agent',
    created_at TEXT DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE public.employes (
    id TEXT PRIMARY KEY,
    matricule TEXT UNIQUE,
    prenom TEXT,
    nom TEXT,
    service TEXT,
    fonction TEXT,
    badge TEXT,
    niveau TEXT,
    statut TEXT,
    creation TEXT,
    atlas_id INTEGER,
    site_id INTEGER,
    site_nom TEXT,
    groupe TEXT,
    date_affectation TEXT,
    created_by TEXT
);

CREATE TABLE public.visiteurs (
    id TEXT PRIMARY KEY,
    prenom TEXT,
    nom TEXT,
    societe TEXT,
    hote TEXT,
    motif TEXT,
    arrivee TEXT,
    badge TEXT,
    statut TEXT,
    created_by TEXT
);

CREATE TABLE public.vehicules (
    id TEXT PRIMARY KEY,
    plaque TEXT,
    type TEXT,
    conducteur TEXT,
    societe TEXT,
    motif TEXT,
    entree TEXT,
    sortie TEXT,
    statut TEXT,
    place_parking TEXT,
    lapi_photo TEXT,
    created_by TEXT
);

CREATE TABLE public.pietons (
    id TEXT PRIMARY KEY,
    datetime TEXT,
    nom TEXT,
    badge TEXT,
    type TEXT,
    point TEXT,
    sens TEXT,
    resultat TEXT,
    notes TEXT,
    created_by TEXT
);

CREATE TABLE public.incidents (
    id TEXT PRIMARY KEY,
    ref TEXT UNIQUE,
    datetime TEXT,
    type TEXT,
    lieu TEXT,
    gravite TEXT,
    statut TEXT,
    agent TEXT,
    description TEXT,
    actions TEXT,
    created_by TEXT
);

CREATE TABLE public.badges (
    ref TEXT PRIMARY KEY,
    nom TEXT,
    type TEXT,
    niveau TEXT,
    emis TEXT,
    validite TEXT,
    etat TEXT,
    societe TEXT,
    created_by TEXT
);

CREATE TABLE public.parking_zones (
    zone TEXT PRIMARY KEY,
    nom TEXT,
    total INTEGER,
    reserve INTEGER,
    handicap INTEGER
);

CREATE TABLE public.parking_places (
    num TEXT PRIMARY KEY,
    zone TEXT REFERENCES public.parking_zones(zone) ON UPDATE NO ACTION ON DELETE NO ACTION,
    etat TEXT,
    plaque TEXT
);

CREATE TABLE public.parking_mouvements (
    id TEXT PRIMARY KEY,
    datetime TEXT,
    plaque TEXT,
    place TEXT,
    zone TEXT,
    action TEXT,
    duree INTEGER,
    created_by TEXT
);

CREATE TABLE public.main_courante (
    id TEXT PRIMARY KEY,
    datetime TEXT,
    poste TEXT,
    agent TEXT,
    type TEXT,
    lieu TEXT,
    description TEXT,
    priorite TEXT,
    created_by TEXT
);

CREATE TABLE public.lapi_lectures (
    id TEXT PRIMARY KEY,
    datetime TEXT,
    plaque_detectee TEXT,
    plaque_raw TEXT,
    confiance INTEGER,
    image TEXT,
    statut TEXT,
    action TEXT,
    created_by TEXT
);

CREATE TABLE public.parametres (
    cle TEXT PRIMARY KEY,
    valeur TEXT
);

CREATE INDEX idx_employes_atlas ON public.employes(atlas_id);
CREATE INDEX idx_employes_site ON public.employes(site_id);
CREATE INDEX idx_pietons_dt ON public.pietons(datetime);
CREATE INDEX idx_incidents_dt ON public.incidents(datetime);
CREATE INDEX idx_vehicules_entree ON public.vehicules(entree);
CREATE INDEX idx_mc_dt ON public.main_courante(datetime);
CREATE INDEX idx_lapi_dt ON public.lapi_lectures(datetime);
-- Supports the historical WHERE zone query and the referencing side of the FK.
CREATE INDEX idx_parking_places_zone ON public.parking_places(zone);
