-- PG-2.3: historical Alert Core schema, no service/permission/lifecycle changes.
-- Keep historical column order, TEXT dates/JSON and user references without FKs.
CREATE TABLE public.security_alerts (
    id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    site TEXT NOT NULL,
    zone TEXT NOT NULL,
    type TEXT NOT NULL,
    level INTEGER NOT NULL CHECK (level BETWEEN 1 AND 4),
    origin TEXT NOT NULL,
    created_by INTEGER NOT NULL,
    username TEXT NOT NULL,
    status TEXT NOT NULL,
    owner TEXT,
    acknowledged_at TEXT,
    resolved_at TEXT,
    comment TEXT NOT NULL DEFAULT '',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    equipment TEXT NOT NULL DEFAULT '',
    cancellation_requested INTEGER NOT NULL DEFAULT 0,
    escalation_step INTEGER NOT NULL DEFAULT 0,
    policy TEXT NOT NULL
);

CREATE TABLE public.alert_audit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id TEXT NOT NULL REFERENCES public.security_alerts(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    created_at TEXT NOT NULL,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    detail TEXT NOT NULL
);

CREATE TABLE public.alert_notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id TEXT NOT NULL REFERENCES public.security_alerts(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    user_id INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    message TEXT NOT NULL,
    read_at TEXT
);

CREATE TABLE public.alert_config_audit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    actor TEXT NOT NULL,
    previous TEXT NOT NULL,
    current TEXT NOT NULL
);

CREATE TABLE public.alert_rules (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    config TEXT NOT NULL
);

CREATE INDEX alert_status_idx ON public.security_alerts(status, level, created_at);
CREATE INDEX alert_notification_user_idx ON public.alert_notifications(user_id, id);
CREATE INDEX alert_audit_alert_id_idx ON public.alert_audit(alert_id, id);
CREATE INDEX alert_notifications_alert_id_idx ON public.alert_notifications(alert_id);

-- No elevated privileges, dynamic SQL or dependency on an application search_path.
CREATE FUNCTION securisite_meta.reject_alert_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog
AS $audit$
BEGIN
    RAISE EXCEPTION 'Audit immuable' USING ERRCODE = '23514';
END;
$audit$;
REVOKE ALL ON FUNCTION securisite_meta.reject_alert_audit_mutation() FROM PUBLIC;

CREATE TRIGGER alert_audit_no_mutation
BEFORE UPDATE OR DELETE ON public.alert_audit
FOR EACH ROW EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

CREATE TRIGGER alert_audit_no_truncate
BEFORE TRUNCATE ON public.alert_audit
FOR EACH STATEMENT EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

CREATE TRIGGER alert_config_audit_no_mutation
BEFORE UPDATE OR DELETE ON public.alert_config_audit
FOR EACH ROW EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

CREATE TRIGGER alert_config_audit_no_truncate
BEFORE TRUNCATE ON public.alert_config_audit
FOR EACH STATEMENT EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

-- The only seed in 002: exact JSON consumed by the existing Alert Core.
INSERT INTO public.alert_rules (id, config)
VALUES (1, '{"escalation":[30,60,120],"incidentCritical":true,"badgeThreshold":3,"badgeWindowSeconds":120}');
