-- PG-7 : appartenances utilisateur ↔ périmètre ↔ rôle, et leur journal
-- append-only. Schéma + contraintes + backfill local + provisioning
-- transactionnel. AUCUNE activation de visibilité multitenant (aucun contrôle
-- d'accès applicatif branché ; aucune RLS — lots PG-8 / PG-9).

-- Cible des clés étrangères composites de memberships vers une zone.
ALTER TABLE public.zones
  ADD CONSTRAINT zones_id_site_tenant_key UNIQUE (id, site_id, tenant_id);

CREATE TABLE public.memberships (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INTEGER NOT NULL REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    site_id UUID,
    zone_id UUID,
    role TEXT NOT NULL CHECK (role IN ('soc', 'client_manager', 'supervisor', 'site_manager', 'agent', 'client_viewer')),
    alert_access TEXT NOT NULL DEFAULT 'own' CHECK (alert_access IN ('own', 'scope')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'archived')),
    -- Niveau de périmètre, dérivé et toujours cohérent.
    scope TEXT GENERATED ALWAYS AS (
      CASE WHEN zone_id IS NOT NULL THEN 'zone'
           WHEN site_id IS NOT NULL THEN 'site'
           ELSE 'tenant' END
    ) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Une zone implique un site.
    CONSTRAINT memberships_zone_needs_site_chk CHECK (zone_id IS NULL OR site_id IS NOT NULL),
    -- site_id (s'il est présent) appartient à tenant_id.
    CONSTRAINT memberships_site_tenant_fk FOREIGN KEY (site_id, tenant_id)
        REFERENCES public.sites (id, tenant_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    -- zone_id (s'il est présent) appartient au couple (site_id, tenant_id).
    CONSTRAINT memberships_zone_parent_fk FOREIGN KEY (zone_id, site_id, tenant_id)
        REFERENCES public.zones (id, site_id, tenant_id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- Unicité par niveau de périmètre : une appartenance (user, tenant, role) au
-- plus par niveau tenant / site / zone.
CREATE UNIQUE INDEX memberships_tenant_level_key ON public.memberships (user_id, tenant_id, role)
  WHERE site_id IS NULL AND zone_id IS NULL;
CREATE UNIQUE INDEX memberships_site_level_key ON public.memberships (user_id, tenant_id, site_id, role)
  WHERE site_id IS NOT NULL AND zone_id IS NULL;
CREATE UNIQUE INDEX memberships_zone_level_key ON public.memberships (user_id, tenant_id, site_id, zone_id, role)
  WHERE zone_id IS NOT NULL;
CREATE INDEX memberships_user_status_idx ON public.memberships (user_id, status);
CREATE INDEX memberships_tenant_status_role_idx ON public.memberships (tenant_id, status, role);
CREATE INDEX memberships_site_idx ON public.memberships (site_id) WHERE site_id IS NOT NULL;
CREATE INDEX memberships_zone_idx ON public.memberships (zone_id) WHERE zone_id IS NOT NULL;

CREATE TABLE public.membership_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id UUID NOT NULL REFERENCES public.memberships(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    user_id INTEGER NOT NULL,
    tenant_id UUID NOT NULL,
    actor_user_id INTEGER,
    action TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    detail JSONB NOT NULL
);
CREATE INDEX membership_audit_membership_idx ON public.membership_audit (membership_id, id);

-- ── Fonctions de garde (search_path figé, SECURITY INVOKER) ───────────────────
CREATE FUNCTION securisite_meta.reject_membership_mutation()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog
AS $membership$
BEGIN
    RAISE EXCEPTION 'Appartenance immuable : archiver (status) au lieu de supprimer ou réidentifier' USING ERRCODE = '23514';
END;
$membership$;
REVOKE ALL ON FUNCTION securisite_meta.reject_membership_mutation() FROM PUBLIC;

CREATE FUNCTION securisite_meta.membership_touch()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog
AS $touch$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$touch$;
REVOKE ALL ON FUNCTION securisite_meta.membership_touch() FROM PUBLIC;

CREATE FUNCTION securisite_meta.membership_audit_write()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog
AS $audit$
DECLARE
    actor integer := NULLIF(current_setting('securisite.actor_user_id', true), '')::integer;
BEGIN
    INSERT INTO public.membership_audit (membership_id, user_id, tenant_id, actor_user_id, action, detail)
    VALUES (
        NEW.id, NEW.user_id, NEW.tenant_id, actor,
        CASE WHEN TG_OP = 'INSERT' THEN 'CREATE' ELSE 'UPDATE' END,
        jsonb_build_object(
            'origin', COALESCE(NULLIF(current_setting('securisite.audit_origin', true), ''), 'sql'),
            'before', CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
            'after', to_jsonb(NEW)
        )
    );
    RETURN NULL;
END;
$audit$;
REVOKE ALL ON FUNCTION securisite_meta.membership_audit_write() FROM PUBLIC;

-- ── Triggers ────────────────────────────────────────────────────────────────
CREATE TRIGGER memberships_no_delete
BEFORE DELETE ON public.memberships
FOR EACH ROW EXECUTE FUNCTION securisite_meta.reject_membership_mutation();

CREATE TRIGGER memberships_identity_lock
BEFORE UPDATE ON public.memberships
FOR EACH ROW
WHEN (NEW.id IS DISTINCT FROM OLD.id
   OR NEW.user_id IS DISTINCT FROM OLD.user_id
   OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
   OR NEW.created_at IS DISTINCT FROM OLD.created_at)
EXECUTE FUNCTION securisite_meta.reject_membership_mutation();

CREATE TRIGGER memberships_touch_updated_at
BEFORE UPDATE ON public.memberships
FOR EACH ROW EXECUTE FUNCTION securisite_meta.membership_touch();

CREATE TRIGGER memberships_audit_insert
AFTER INSERT ON public.memberships
FOR EACH ROW EXECUTE FUNCTION securisite_meta.membership_audit_write();

CREATE TRIGGER memberships_audit_update
AFTER UPDATE ON public.memberships
FOR EACH ROW EXECUTE FUNCTION securisite_meta.membership_audit_write();

CREATE TRIGGER membership_audit_no_mutation
BEFORE UPDATE OR DELETE ON public.membership_audit
FOR EACH ROW EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

CREATE TRIGGER membership_audit_no_truncate
BEFORE TRUNCATE ON public.membership_audit
FOR EACH STATEMENT EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

-- ── Backfill local ──────────────────────────────────────────────────────────
-- Une appartenance de niveau tenant par utilisateur admin/agent existant, sous
-- le tenant « local » : admin -> soc (accès scope), agent -> agent (accès own).
-- Jamais de réactivation ni d'élargissement (ON CONFLICT DO NOTHING).
INSERT INTO public.memberships (user_id, tenant_id, role, alert_access)
SELECT u.id,
       (SELECT id FROM public.tenants WHERE code = 'local'),
       CASE u.role WHEN 'admin' THEN 'soc' ELSE 'agent' END,
       CASE u.role WHEN 'admin' THEN 'scope' ELSE 'own' END
FROM public.users u
WHERE u.role IN ('admin', 'agent')
ON CONFLICT (user_id, tenant_id, role) WHERE site_id IS NULL AND zone_id IS NULL DO NOTHING;
