-- PG-10 : journal de sécurité global transversal (QUI/QUOI/QUAND/QUELLE
-- RESSOURCE/QUEL PÉRIMÈTRE/QUEL RÉSULTAT), distinct des journaux spécialisés
-- alert_audit / alert_config_audit / membership_audit qui restent l'autorité
-- de leur domaine (before/after détaillé) — security_audit n'enregistre que
-- l'événement de sécurité synthétique.

CREATE TABLE public.security_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    request_id TEXT,
    correlation_id TEXT,
    -- Pas de FOREIGN KEY vers users : un login échoué (utilisateur inconnu) ou
    -- un événement post-suppression de compte doit rester journalisable.
    actor_user_id INTEGER,
    actor_username TEXT,
    actor_role TEXT,
    -- Pas de FOREIGN KEY vers tenants/sites/zones : posés par le périmètre
    -- résolu côté serveur (jamais le corps de la requête), peuvent être NULL
    -- (login, refus avant toute résolution de périmètre).
    tenant_id UUID,
    site_id UUID,
    zone_id UUID,
    event_type TEXT NOT NULL CHECK (btrim(event_type) <> ''),
    resource_type TEXT NOT NULL CHECK (btrim(resource_type) <> ''),
    resource_id TEXT,
    action TEXT NOT NULL CHECK (btrim(action) <> ''),
    outcome TEXT NOT NULL CHECK (outcome IN ('success', 'denied', 'failure')),
    -- Un IA aura une origine dédiée plus tard (PG-19+) : ajout par migration,
    -- une valeur imprévue est un signal utile, pas une contrainte à assouplir sans réflexion.
    origin TEXT NOT NULL CHECK (origin IN ('http', 'system', 'migration', 'automation')),
    ip_address INET,
    user_agent TEXT,
    detail JSONB
);

CREATE INDEX security_audit_tenant_created_idx ON public.security_audit (tenant_id, created_at DESC);
CREATE INDEX security_audit_actor_created_idx ON public.security_audit (actor_user_id, created_at DESC);
CREATE INDEX security_audit_event_created_idx ON public.security_audit (event_type, created_at DESC);
CREATE INDEX security_audit_resource_created_idx ON public.security_audit (resource_type, resource_id, created_at DESC);

-- ── Append-only (réutilise la garde générique déjà en place pour alert_audit /
-- alert_config_audit / membership_audit — un seul corps, une seule vérité) ──
CREATE TRIGGER security_audit_no_mutation
BEFORE UPDATE OR DELETE ON public.security_audit
FOR EACH ROW EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

CREATE TRIGGER security_audit_no_truncate
BEFORE TRUNCATE ON public.security_audit
FOR EACH STATEMENT EXECUTE FUNCTION securisite_meta.reject_alert_audit_mutation();

-- ── RLS : lecture réservée aux memberships actifs de rôle 'soc' sous leur
-- propre tenant (un simple membership 'agent' ne donne AUCUN accès général au
-- journal global — distinct de current_actor_tenant_ids(), PG-9, qui couvre
-- tout rôle). Écriture non filtrée par RLS : le tenant_id posé par
-- l'application peut légitimement être NULL (login, refus avant résolution
-- de périmètre) — le GRANT (INSERT seul, jamais SELECT en écriture libre)
-- est la vraie porte côté rôle, RLS ne fait ici que restreindre la LECTURE.
CREATE FUNCTION securisite_meta.current_actor_soc_tenant_ids()
RETURNS SETOF uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public
AS $rls$
  SELECT DISTINCT m.tenant_id
  FROM public.memberships m
  JOIN public.tenants t ON t.id = m.tenant_id AND t.status = 'active'
  WHERE m.status = 'active' AND m.role = 'soc'
    AND m.user_id = NULLIF(current_setting('securisite.actor_user_id', true), '')::integer;
$rls$;
REVOKE ALL ON FUNCTION securisite_meta.current_actor_soc_tenant_ids() FROM PUBLIC;

ALTER TABLE public.security_audit ENABLE ROW LEVEL SECURITY;

CREATE POLICY security_audit_soc_read ON public.security_audit
  FOR SELECT USING (tenant_id IN (SELECT securisite_meta.current_actor_soc_tenant_ids()));

CREATE POLICY security_audit_app_insert ON public.security_audit
  FOR INSERT WITH CHECK (true);
