-- PG-13 : infrastructure push — stockage des abonnements navigateur (Web
-- Push : endpoint + clés p256dh/auth du PushSubscription standard). Aucune
-- donnée de fournisseur tiers ici, aucune clé VAPID : l'activation d'un
-- fournisseur réel reste un HUMAN CHECKPOINT (voir docs/push.md). Un
-- abonnement est un état de périphérique éphémère, pas un enregistrement
-- d'audit : contrairement à memberships (PG-7), il est mis à jour/supprimé
-- librement, ON DELETE CASCADE avec l'utilisateur.

CREATE TABLE public.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE CHECK (btrim(endpoint) <> ''),
    p256dh TEXT NOT NULL CHECK (btrim(p256dh) <> ''),
    auth TEXT NOT NULL CHECK (btrim(auth) <> ''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX push_subscriptions_user_idx ON public.push_subscriptions (user_id);
